### ISSUE TITLE
haskell-tor-0.1.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [GaloisInc/haskell-tor#4]
Citing from http://hydra.cryp.to/build/1378058/log/raw:

~~~~~
Preprocessing executable 'haskell-tor' for haskell-tor-0.1.0.0...

exe/Main.hs:6:8:
    Could not find module ‘Tor.Flags’
    Use -v to see a list of the files searched for.
~~~~~

**Comment by acw** [comment]
This is an annoying packaging problem, where `cabal sdist` failed to pick up a file. (Admittedly, because I forgot to mention it, but I'm going to blame the computer.)

I'm packaging up some other Cabal changes to fix some other issues. I'll update this ticket when I post the resulting changes to Hackage.

**Comment by acw** [comment]
I've uploaded a new version (0.1.1) which should compile out of the box, and I think I've added something to the Travis-CI test that will ensure that this sdist problem doesn't happen again. However, can you try to install again to test this, and close the ticket if it works?

**Comment by peti** [comment]
The new version fixes the issue with the missing module. Thank you very much! Unfortunately, we still can't compile the package on NixOS because it depends on some outdated versions of its build inputs http://packdeps.haskellers.com/feed?needle=haskell-tor, but that's another issue.
